#include <filesystem>

#include "fmt/os.h"
#include "libcufetch/common.hh"
#include "stateManager.hpp"

StateManager::StateManager()
{
    if (!std::filesystem::exists(m_path))
    {
        auto f = fmt::output_file(m_path.string(), fmt::file::WRONLY | fmt::file::TRUNC | fmt::file::CREATE);
        f.print(R"(# AUTOGENERATED FILE. DO NOT EDIT THIS FILE.
# YOU GONNA MESS SHIT UP. unless you know what you doing ofc
                )");
        f.close();
    }

    try
    {
        if (m_state.empty())
            m_state = toml::parse_file(m_path.string());
    }
    catch (const toml::parse_error& err)
    {
        die(_("Failed to parse state file at '{}':\n"
              "{}\n"
              "\t(error occurred at line {} column {})"),
            m_path.string(), err.description(),
            err.source().begin.line, err.source().begin.column);
    }
}
