name: Makefile CI (Test customfetch NOGUI)

on:
  push:
    branches: [ "main", "test", "windows" ]
  pull_request:
    branches: [ "main", "test", "windows" ]

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: create tmp directory
      run: mkdir /tmp/customfetch-0.8.6.orig

    - name: Install Packages
      run: sudo apt-get update && sudo apt-get install libwayland-dev binutils lintian debhelper devscripts debmake autoconf automake autotools-dev dh-make fakeroot xutils pbuilder -y

    - name: Clean
      run: make clean

    - name: Create deb
      run: |
        cp -r $GITHUB_WORKSPACE /tmp/customfetch-0.8.6.orig
        cd /tmp/customfetch-0.8.6.orig/customfetch
        mkdir -p Debian/Debhelper/Buildsystem/
        wget https://github.com/Debian/debhelper/raw/master/lib/Debian/Debhelper/Buildsystem/makefile.pm -O Debian/Debhelper/Buildsystem/make.pm
        sed -i "s#package Debian::Debhelper::Buildsystem::makefile#package Debian::Debhelper::Buildsystem::make#g" Debian/Debhelper/Buildsystem/make.pm
        dpkg-buildpackage -us -uc

    - name: Install test cufetch
      run: |
        cd /tmp/customfetch-0.8.6.orig
        sudo dpkg -i customfetch_0.8.6-1_amd64.deb
        cufetch
  
  build_ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Packages
      run: sudo apt-get update && sudo apt-get install build-essential cmake neofetch tree libgtk-3-dev pkg-config libgtkmm-3.0-dev libprocps-dev -y
    
    - name: Clean
      run: make clean

    - name: Compile
      run: sudo make install DEBUG=1 VENDOR_TEST=1 GUI_MODE=0

    - name: Test neofetch
      run: neofetch

    - name: Check system values
      run: |
        ls -l /sys/devices/virtual/dmi/id/ /sys/class/dmi/id/
        grep -Eri "virtual" /sys/class/dmi/id/ || true
        cat /sys/devices/virtual/dmi/id/board_name /sys/devices/virtual/dmi/id/board_vendor /sys/devices/virtual/dmi/id/board_version
        tree /sys/devices/system/cpu/cpu0/
        printf "/etc/os-release\n" && cat /etc/os-release
        printf "getting 0x5353 hexcode\n" && grep -nri "5353" /sys/class/ || true
       
    - name: Test customfetch
      run: ./build/debug/cufetch

  build_Arch-AUR:
  
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - uses: actions/checkout@v4

    - name: Install the packages
      run: pacman -Syyu git sudo base-devel fakeroot pkgconf tree neofetch libprocps --noconfirm --needed
    
    - name: get /etc/sudoers
      run: |
        sed -i "s#root ALL=(ALL:ALL) ALL#root ALL=(ALL:ALL) NOPASSWD: ALL\nnobody ALL=(ALL:ALL) NOPASSWD: ALL#g" /etc/sudoers
        cat /etc/sudoers
    - name: get /etc/makepkg.conf
      run: |
        sed -i "s#purge debug lto#purge !debug lto#" /etc/makepkg.conf
        cat /etc/makepkg.conf

    - name: Build and install using makepkg
      run: |
        git clone https://aur.archlinux.org/customfetch-git.git
        chown -R nobody customfetch-git
        cd customfetch-git
        sudo -u nobody makepkg -si --noconfirm

    - name: Test neofetch
      run: neofetch

    - name: Test customfetch
      run: cufetch

  build_Arch:
  
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - uses: actions/checkout@v4

    - name: Install the packages
      run: pacman -Syyu git sudo binutils gdb base-devel fakeroot pkgconf tree neofetch fastfetch libprocps --noconfirm --needed
    
    - name: get /etc/sudoers
      run: |
        sed -i "s#root ALL=(ALL:ALL) ALL#root ALL=(ALL:ALL) NOPASSWD: ALL\nnobody ALL=(ALL:ALL) NOPASSWD: ALL#g" /etc/sudoers
        cat /etc/sudoers
    - name: get /etc/makepkg.conf
      run: |
        sed -i "s#purge debug lto#purge !debug lto#" /etc/makepkg.conf
        cat /etc/makepkg.conf

    - name: Clean
      run: make clean

    - name: Compile
      run: make install DEBUG=1 VENDOR_TEST=1 GUI_MODE=0

    - name: Test neofetch
      run: neofetch

    - name: Test fastfetch
      run: fastfetch

    - name: Check system values
      run: |
        ls -l /sys/devices/virtual/dmi/id/ /sys/class/dmi/id/
        grep -Eri "virtual" /sys/class/dmi/id/ || true
        cat /sys/devices/virtual/dmi/id/board_name /sys/devices/virtual/dmi/id/board_vendor /sys/devices/virtual/dmi/id/board_version
        tree /sys/devices/system/cpu/cpu0/
        printf "/etc/os-release\n" && cat /etc/os-release

    #- name: Setup SSH session
    #  uses: mxschmitt/action-tmate@v3

    - name: Test customfetch
      run: ./build/debug/cufetch
