name: Makefile CI (Test customfetch)

on:
  push:
    branches: [ "main", "test", "windows" ]
  pull_request:
    branches: [ "main", "test", "windows" ]

jobs:
  build_ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Packages
      run: sudo apt-get update && sudo apt-get install build-essential cmake neofetch tree libgtk-3-dev pkg-config libpci-dev libgtkmm-3.0-dev -y
    
    - name: Clean
      run: make clean

    - name: Compile
      run: sudo make install DEBUG=1 VENDOR_TEST=1 GUI_SUPPORT=0

    - name: Test neofetch
      run: neofetch

    - name: Check system values
      run: |
        ls -l /sys/devices/virtual/dmi/id/ /sys/class/dmi/id/
        grep -Eri "virtual" /sys/class/dmi/id/ || true
        cat /sys/devices/virtual/dmi/id/board_name /sys/devices/virtual/dmi/id/board_vendor /sys/devices/virtual/dmi/id/board_version
        tree /sys/devices/system/cpu/cpu0/
        printf "/etc/os-release\n" && cat /etc/os-release
       
    - name: Test customfetch
      run: ./build/debug/cufetch

  build_Arch-AUR:
  
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - uses: actions/checkout@v4

    - name: Install the packages
      run: pacman -Syyu git sudo base-devel fakeroot pkgconf tree neofetch --noconfirm --needed
    
    - name: get /etc/sudoers
      run: |
        sed -i "s#root ALL=(ALL:ALL) ALL#root ALL=(ALL:ALL) NOPASSWD: ALL\nnobody ALL=(ALL:ALL) NOPASSWD: ALL#g" /etc/sudoers
        cat /etc/sudoers
    - name: get /etc/makepkg.conf
      run: |
        sed -i "s#purge debug lto#purge !debug lto#" /etc/makepkg.conf
        cat /etc/makepkg.conf

    - name: Build and install using makepkg
      run: |
        git clone https://aur.archlinux.org/customfetch-git.git
        chown -R nobody customfetch-git
        cd customfetch-git
        sudo -u nobody makepkg -si --noconfirm

    - name: Test neofetch
      run: neofetch

    - name: Test customfetch
      run: cufetch
      
  build_Arch:
  
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - uses: actions/checkout@v4

    - name: Install the packages
      run: pacman -Syyu git sudo base-devel fakeroot pkgconf tree neofetch fastfetch --noconfirm --needed
    
    - name: get /etc/sudoers
      run: |
        sed -i "s#root ALL=(ALL:ALL) ALL#root ALL=(ALL:ALL) NOPASSWD: ALL\nnobody ALL=(ALL:ALL) NOPASSWD: ALL#g" /etc/sudoers
        cat /etc/sudoers
    - name: get /etc/makepkg.conf
      run: |
        sed -i "s#purge debug lto#purge !debug lto#" /etc/makepkg.conf
        cat /etc/makepkg.conf

    - name: Clean
      run: make clean

    - name: Compile
      run: make install DEBUG=1 VENDOR_TEST=1 GUI_SUPPORT=0

    - name: Test neofetch
      run: neofetch

    - name: Test fastfetch
      run: fastfetch

    - name: Check system values
      run: |
        ls -l /sys/devices/virtual/dmi/id/ /sys/class/dmi/id/
        grep -Eri "virtual" /sys/class/dmi/id/ || true
        cat /sys/devices/virtual/dmi/id/board_name /sys/devices/virtual/dmi/id/board_vendor /sys/devices/virtual/dmi/id/board_version
        tree /sys/devices/system/cpu/cpu0/
        printf "/etc/os-release\n" && cat /etc/os-release
       
    - name: Test customfetch
      run: ./build/debug/cufetch


  build_Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup-msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: git make mingw-w64-clang-x86_64-7zip mingw-w64-clang-x86_64-make mingw-w64-clang-x86_64-clang

      - name: print msys version
        run: uname -a

      - name: Build
        run: make clean && make CXX=clang++ DEBUG=1 VENDOR_TEST=1 GUI_SUPPORT=0 #|| mingw-w64-clang-x86_64-make clean && mingw-w64-clang-x86_64-make DEBUG=1 VENDOR_TEST=1 GUI_SUPPORT=0

      - name: Test customfetch
        run: ./build/debug/cufetch -s "windows 11"
